apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kv-store
  name: kv-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-store
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kv-store
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.gitlab.com/mfcekirdek/in-memory-store/main:latest
        name: main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: APP_NAME
            value: "kv-store"
          - name: IS_DEBUG
            value: "true"
          - name: STORAGE_DIR_PATH
            value: "storage"
          - name: SAVE_TO_FILE_INTERVAL
            value: "60"
          - name: PORT
            value: "8080"
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kv-store
  name: kv-store
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: kv-store
  type: NodePort
#  type: LoadBalancer
status:
  loadBalancer: {}
