image: golang:1.16-alpine3.14

stages:
    - test
    - build
    - dockerize
    - deploy

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."

lint-test-job:
  image: golangci/golangci-lint:v1.41.1
  stage: test
  variables:
    LINT_TIMEOUT: 5m
    LINT_CONFIG_PATH: "configs/linter/.golangci.yml"
    EXTRA_PARAMETERS: ""
  script:
    - golangci-lint run -c $LINT_CONFIG_PATH -v --timeout $LINT_TIMEOUT $EXTRA_PARAMETERS --fix

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."

dockerize-job:   # This job also runs in the test stage.
  stage: dockerize    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Dockerizing the app..."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."